Fix lib_gen.c
Fixes these kind of errors on MSVC
../ncurses/lib_gen.c(23): error C2059: syntax error: '('

(required for static build)

../ncurses/lib_gen.c(30): error C2059: syntax error: '('
../ncurses/lib_gen.c(37): error C2059: syntax error: '('
../ncurses/lib_gen.c(44): error C2059: syntax error: '('
../ncurses/lib_gen.c(51): error C2059: syntax error: '('
../ncurses/lib_gen.c(58): error C2059: syntax error: '('
../ncurses/lib_gen.c(65): error C2059: syntax error: '('
../ncurses/lib_gen.c(72): error C2059: syntax error: '('
../ncurses/lib_gen.c(79): error C2059: syntax error: '('
../ncurses/lib_gen.c(86): error C2059: syntax error: '('
(and more)